# Generated by Django 4.1.3 on 2022-11-23 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_remove_profile_user_profile_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='user',
        ),
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
    ]
