# Generated by Django 4.1.3 on 2022-11-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_remove_choice_user_remove_question_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=5),
        ),
    ]
