# Generated by Django 4.1.3 on 2022-11-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_remove_choice_votes_alter_choice_choice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ('text',)},
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='created',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='title',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='username',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(max_length=200),
        ),
    ]
