# Generated by Django 4.1.3 on 2022-11-23 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_alter_feedback_options_remove_feedback_created_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedbackComment',
        ),
    ]
